### ISSUE TITLE
Bug: Duplicate Incident reported for non-duplicate incident

### ISSUE THREAD

**Issue by atharvjoshi** [AY1920S1-CS2103-T11-1/main#113]
If I save an incident locally, close the app, reopen the app, and try creating a new incident, the app reports that I am trying to create a duplicate incident. This has something to do with how we are comparing incidents according to ID. Looks like the incident counter is resetting to 0 whereas it should remember its previous state (before app is closed).

**Comment by madanalogy** [comment]
This should have been temporarily solved with my edit in PR #106 since incidents are now compared via dateTime instead of ID

**Comment by atharvjoshi** [comment]
Yes, i just realised the same too. isSameIncident() is being used by uniqueIncidentList to check contains() method.

**Comment by atharvjoshi** [comment]
For now, this bug has been addressed. There is however a peculiar side effect - the test `JsonSerializableIncidentManagerTest` now only passes when the incidents in `duplicateEntityIncidentManager.json` are different (i.e. when their dateTime is different)...
