### ISSUE TITLE
Update User Guide

### ISSUE THREAD

**Issue by madanalogy** [AY1920S1-CS2103-T11-1/main#15]
https://nus-cs2103-ay1920s1.github.io/website/schedule/week7/project.html#2-update-ug

**Comment by atharvjoshi** [comment]
Submitted pull request with commit that will add report 'filling' and 'submitting' features to UG (section 3.1 and 3.2). Sections 1 and 2 have been edited to reflect IMS-related information as well. The other sections (Except 3.1 and 3.2) still reflect AB3-related information.

**Comment by madanalogy** [comment]
Submitted pull request with commit to add 'login' feature to UG. Edited 'add' feature to reflect new indented utilisation of persons in IMS.
