### ISSUE TITLE
More PED issues

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103-T11-1/main#259]
https://github.com/yuhongtay/ped/issues/4
https://github.com/yuhongtay/ped/issues/5
https://github.com/yuhongtay/ped/issues/6
https://github.com/yuhongtay/ped/issues/7
https://github.com/yuhongtay/ped/issues/8
https://github.com/yuhongtay/ped/issues/9

**Comment by madanalogy** [comment]
Other than number 4 (which is similar to #245), the rest deal with vehicles/editing of incidents

**Comment by tirameshu** [comment]
@hellopanda128 I tested number 5 but could not recreate the problem. I was first prompted to change caller number to 8 digits, but after changing to that I found another bug. edit-i (and other commands as well) should check for irrelevant prefixes. else there would be null pointer.
