### ISSUE TITLE
As a user I want to autofill my details when creating a report

### ISSUE THREAD

**Issue by madanalogy** [AY1920S1-CS2103-T11-1/main#53]
... so that I would be able to create a report faster

**Comment by madanalogy** [comment]
Method to retrieve logged in person details available from model. Refer to PR #66

**Comment by atharvjoshi** [comment]
With PR #110, the fields 'operator', 'incidentDateTime', 'id' and 'location' are auto-filled. The field 'vehicle' is the only field yet to be auto-filled. We expect it to be auto-filled (thus resolving this issue) after @tirameshu completes vehicle assignment.

**Comment by madanalogy** [comment]
Vehicle dispatch completed in PR #133
